apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: data-src
spec:
  image: docker.io/matzew/data-src
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: inputchannel
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: read-subscription
  namespace: myproject
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: inputchannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: data-processor
  reply:
    channel:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: replychannel
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: reply-subscription
  namespace: myproject
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: replychannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: data-sink




