apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: dumpy
  namespace: myproject
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            imagePullPolicy: IfNotPresent
            image: docker.io/matzew/openshift-message-dumper
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: reply 
  namespace: myproject
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            imagePullPolicy: IfNotPresent
            image: docker.io/matzew/vertx-reply
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: inputchannel
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: replychannel
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: urbanobservatory-api
spec:
  hosts:
  - api.usb.urbanobservatory.ac.uk
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: urbanobservatory-api
spec:
  hosts:
  - api.usb.urbanobservatory.ac.uk
  tls:
  - match:
    - port: 443
      sni_hosts:
      - api.usb.urbanobservatory.ac.uk
    route:
    - destination:
        host: api.usb.urbanobservatory.ac.uk
        port:
          number: 443
      weight: 100
---
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: urbanobservatory-event-source
spec:
  image: docker.io/markusthoemmes/knative-websocket-eventsource
  args: 
    - '--source=wss://api.usb.urbanobservatory.ac.uk/stream'
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: inputchannel
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: readws-subscription
  namespace: myproject
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: inputchannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: reply
  reply:
    channel:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: replychannel
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: reply-subscription
  namespace: myproject
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: replychannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: dumpy




